version: '3'

services:
  docker-coralnet:
    container_name: coral-node
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - coralnet.env
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - coralnet-data:/.corald
volumes:
  coralnet-data:



