{
 "title": "cosmos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Block Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds"
    }
   ]
  },
  {
   "title": "Height",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height"
    }
   ]
  },
  {
   "title": "Indexed Txs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  code AS \"time\",\n  code\nFROM transaction\nWHERE\n  $__unixEpochFilter(code)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators"
    }
   ]
  }
 ]
}